componentScriptContent: 
  - xmlizable: 
    - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      â†’: |
        /*Begin_c8o_AppImport*/
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        /* Uncomment the following lines to enable the i18n feature.
                         * You should add a json per language in the assets/i18n folder. */
                        translate.setDefaultLang('en');
                        translate.use(translate.getBrowserLang());
                        
                        /* Uncomment the following lines to enable the custom status bar color. */
                        // statusBar.overlaysWebView(false);
                        // statusBar.backgroundColorByHexString("#000000");
                        // statusBar.styleBlackOpaque();
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        
tplProjectName: C8oStudio
â†“Menu [mobile.components.UIDynamicMenu-1500890597895]: ðŸ— mobileMenus/Menu.yaml
â†“CodeEditor [mobile.components.UISharedComponent-1587900690141]: ðŸ— mobileSharedComponents/CodeEditor.yaml
â†“Properties [mobile.components.UISharedComponent-1587904783890]: ðŸ— mobileSharedComponents/Properties.yaml
â†“TreeView [mobile.components.UISharedComponent-1587912746555]: ðŸ— mobileSharedComponents/TreeView.yaml
â†“CodeEditor [mobile.components.PageComponent-1500538678074]: ðŸ— mobilePages/CodeEditor.yaml
â†“Layout [mobile.components.PageComponent-1587821570783]: ðŸ— mobilePages/Layout.yaml
â†“Properties [mobile.components.PageComponent-1587904800779]: ðŸ— mobilePages/Properties.yaml
â†“LogViewer [mobile.components.PageComponent-1587905682093]: ðŸ— mobilePages/LogViewer.yaml
â†“Projects [mobile.components.PageComponent-1587913187659]: ðŸ— mobilePages/Projects.yaml
â†“Theme [mobile.components.UITheme-1491635018260]: 
  comment: Global color themes can be customized here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '// Ionic Variables and Theming. For more info, please see:
          // http://ionicframework.com/docs/v2/theming/ 
          $font-path: "../assets/fonts";
          
          @import "ionic.globals";
          
          
          // Shared Variables
          // --------------------------------------------------
          // To customize the look and feel of this app, you can override
          // the Sass variables found in Ionic''s source scss files.
          // To view all the possible Ionic variables, see:
          // http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
          
          
          
          
          // Named Color Variables
          // --------------------------------------------------
          // Named colors makes it easy to reuse colors on various components.
          // It''s highly recommended to change the default colors
          // to match your app''s branding. Ionic uses a Sass map of
          // colors so you can add, rename and remove colors as needed.
          // The "primary" color is the only required color in the map.
          
          $colors: (
                  primary:    #387ef5,
                  secondary:  #32db64,
                  danger:     #f53d3d,
                  light:      #f4f4f4,
                  dark:       #222
          );
          
          
          // App iOS Variables
          // --------------------------------------------------
          // iOS only Sass variables can go here
          
          
          
          
          // App Material Design Variables
          // --------------------------------------------------
          // Material Design only Sass variables can go here
          
          
          
          
          // App Windows Variables
          // --------------------------------------------------
          // Windows only Sass variables can go here
          
          
          
          
          // App Theme
          // --------------------------------------------------
          // Ionic apps can have different themes applied, which can
          // then be future customized. This import comes last
          // so that the above variables are used and Ionic''s
          // default are overridden.
          
          @import "ionic.theme.default";
          @import "../../node_modules/ag-grid-community/dist/styles/ag-grid.scss";
          @import "../../node_modules/ag-grid-community/dist/styles/ag-theme-balham-dark/sass/ag-theme-balham-dark.scss";
          
          // Ionicons
          // --------------------------------------------------
          // The premium icon font for Ionic. For more info, please see:
          // http://ionicframework.com/docs/v2/ionicons/
          
          @import "ionic.ionicons";
          
          
          // Fonts
          // --------------------------------------------------
          
          @import "roboto";
          @import "noto-sans";
          '
â†“Style [mobile.components.UIStyle-1491635462437]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '.content {
          	/* add some styling CSS rules here for the body of your app
          	   for example,
          	 		background-color: your color; 
          	 		background-image: url(some background image);
          	*/
          }
          
          .toolbar-background {
          	/* add some styling CSS rules here for the Headers and Footers
          	   for example,
          	 		background-color: your color; 
          	*/
          }
          
          /* All GoldenLayout styles goes there goes there */
          .lm_root{position:relative}.lm_row>.lm_item{float:left}.lm_content{overflow:hidden;position:relative}.lm_dragging,.lm_dragging *{cursor:move !important;user-select:none}.lm_maximised{position:absolute;top:0;left:0;z-index:40}.lm_maximise_placeholder{display:none}.lm_splitter{position:relative;z-index:20}.lm_splitter:hover,.lm_splitter.lm_dragging{background:orange}.lm_splitter.lm_vertical .lm_drag_handle{width:100%;position:absolute;cursor:ns-resize}.lm_splitter.lm_horizontal{float:left;height:100%}.lm_splitter.lm_horizontal .lm_drag_handle{height:100%;position:absolute;cursor:ew-resize}.lm_header{overflow:visible;position:relative;z-index:1}.lm_header [class^=lm_]{box-sizing:content-box !important}.lm_header .lm_controls{position:absolute;right:3px}.lm_header .lm_controls>li{cursor:pointer;float:left;width:18px;height:18px;text-align:center}.lm_header ul{margin:0;padding:0;list-style-type:none}.lm_header .lm_tabs{position:absolute}.lm_header .lm_tab{cursor:pointer;float:left;height:14px;margin-top:1px;padding:0 10px 5px;padding-right:25px;position:relative}.lm_header .lm_tab i{width:2px;height:19px;position:absolute}.lm_header .lm_tab i.lm_left{top:0;left:-2px}.lm_header .lm_tab i.lm_right{top:0;right:-2px}.lm_header .lm_tab .lm_title{display:inline-block;overflow:hidden;text-overflow:ellipsis}.lm_header .lm_tab .lm_close_tab{width:14px;height:14px;position:absolute;top:0;right:0;text-align:center}.lm_stack.lm_left .lm_header,.lm_stack.lm_right .lm_header{height:100%}.lm_dragProxy.lm_left .lm_header,.lm_dragProxy.lm_right .lm_header,.lm_stack.lm_left .lm_header,.lm_stack.lm_right .lm_header{width:20px;float:left;vertical-align:top}.lm_dragProxy.lm_left .lm_header .lm_tabs,.lm_dragProxy.lm_right .lm_header .lm_tabs,.lm_stack.lm_left .lm_header .lm_tabs,.lm_stack.lm_right .lm_header .lm_tabs{transform-origin:left top;top:0;width:1000px}.lm_dragProxy.lm_left .lm_header .lm_controls,.lm_dragProxy.lm_right .lm_header .lm_controls,.lm_stack.lm_left .lm_header .lm_controls,.lm_stack.lm_right .lm_header .lm_controls{bottom:0}.lm_dragProxy.lm_left .lm_items,.lm_dragProxy.lm_right .lm_items,.lm_stack.lm_left .lm_items,.lm_stack.lm_right .lm_items{float:left}.lm_dragProxy.lm_left .lm_header .lm_tabs,.lm_stack.lm_left .lm_header .lm_tabs{transform:rotate(-90deg) scaleX(-1);left:0}.lm_dragProxy.lm_left .lm_header .lm_tabs .lm_tab,.lm_stack.lm_left .lm_header .lm_tabs .lm_tab{transform:scaleX(-1);margin-top:1px}.lm_dragProxy.lm_left .lm_header .lm_tabdropdown_list,.lm_stack.lm_left .lm_header .lm_tabdropdown_list{top:initial;right:initial;left:20px}.lm_dragProxy.lm_right .lm_content{float:left}.lm_dragProxy.lm_right .lm_header .lm_tabs,.lm_stack.lm_right .lm_header .lm_tabs{transform:rotate(90deg) scaleX(1);left:100%;margin-left:0}.lm_dragProxy.lm_right .lm_header .lm_controls,.lm_stack.lm_right .lm_header .lm_controls{left:3px}.lm_dragProxy.lm_right .lm_header .lm_tabdropdown_list,.lm_stack.lm_right .lm_header .lm_tabdropdown_list{top:initial;right:20px}.lm_dragProxy.lm_bottom .lm_header .lm_tab,.lm_stack.lm_bottom .lm_header .lm_tab{margin-top:0;border-top:none}.lm_dragProxy.lm_bottom .lm_header .lm_controls,.lm_stack.lm_bottom .lm_header .lm_controls{top:3px}.lm_dragProxy.lm_bottom .lm_header .lm_tabdropdown_list,.lm_stack.lm_bottom .lm_header .lm_tabdropdown_list{top:initial;bottom:20px}.lm_drop_tab_placeholder{float:left;width:100px;height:10px;visibility:hidden}.lm_header .lm_controls .lm_tabdropdown:before{content:'''';width:0;height:0;vertical-align:middle;display:inline-block;border-top:5px dashed;border-right:5px solid transparent;border-left:5px solid transparent;color:white}.lm_header .lm_tabdropdown_list{position:absolute;top:20px;right:0;z-index:5;overflow:hidden}.lm_header .lm_tabdropdown_list .lm_tab{clear:both;padding-right:10px;margin:0}.lm_header .lm_tabdropdown_list .lm_tab .lm_title{width:100px}.lm_header .lm_tabdropdown_list .lm_close_tab{display:none !important}.lm_dragProxy{position:absolute;top:0;left:0;z-index:30}.lm_dragProxy .lm_header{background:transparent}.lm_dragProxy .lm_content{border-top:none;overflow:hidden}.lm_dropTargetIndicator{display:none;position:absolute;z-index:20}.lm_dropTargetIndicator .lm_inner{width:100%;height:100%;position:relative;top:0;left:0}.lm_transition_indicator{display:none;width:20px;height:20px;position:absolute;top:0;left:0;z-index:20}.lm_popin{width:20px;height:20px;position:absolute;bottom:0;right:0;z-index:9999}.lm_popin>*{width:100%;height:100%;position:absolute;top:0;left:0}.lm_popin>.lm_bg{z-index:10}.lm_popin>.lm_icon{z-index:20}/*# sourceMappingURL=goldenlayout-base.css.map */
          .lm_goldenlayout{background:#000000}.lm_content{background:#222222}.lm_dragProxy .lm_content{box-shadow:2px 2px 4px rgba(0,0,0,0.9)}.lm_dropTargetIndicator{box-shadow:inset 0 0 30px #000000;outline:1px dashed #cccccc;transition:all 200ms ease}.lm_dropTargetIndicator .lm_inner{background:#000000;opacity:.2}.lm_splitter{background:#000000;opacity:.001;transition:opacity 200ms ease}.lm_splitter:hover,.lm_splitter.lm_dragging{background:#444444;opacity:1}.lm_header{height:20px;user-select:none}.lm_header.lm_selectable{cursor:pointer}.lm_header .lm_tab{font-family:Arial,sans-serif;font-size:12px;color:#999999;background:#111111;box-shadow:2px -2px 2px rgba(0,0,0,0.3);margin-right:2px;padding-bottom:2px;padding-top:2px}.lm_header .lm_tab .lm_close_tab{width:11px;height:11px;background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAYAAADEUlfTAAAATElEQVR4nG3OwQ0DMQwDwZGRBtR/j1YJzMc5+IDoR+yCVO29g+pu981MFgqZmRdAfU7+CYWcbF11LwALjpBL0N0qybNx/RPU+gOeiS/+XCRwDlTgkQAAAABJRU5ErkJggg==);background-position:center center;background-repeat:no-repeat;top:4px;right:6px;opacity:.4}.lm_header .lm_tab .lm_close_tab:hover{opacity:1}.lm_header .lm_tab.lm_active{border-bottom:none;box-shadow:0 -2px 2px #000000;padding-bottom:3px}.lm_header .lm_tab.lm_active .lm_close_tab{opacity:1}.lm_dragProxy.lm_bottom .lm_header .lm_tab,.lm_stack.lm_bottom .lm_header .lm_tab{box-shadow:2px 2px 2px rgba(0,0,0,0.3)}.lm_dragProxy.lm_bottom .lm_header .lm_tab.lm_active,.lm_stack.lm_bottom .lm_header .lm_tab.lm_active{box-shadow:0 2px 2px #000000}.lm_selected .lm_header{background-color:#452500}.lm_tab:hover,.lm_tab.lm_active{background:#222222;color:#dddddd}.lm_header .lm_controls .lm_tabdropdown:before{color:#ffffff}.lm_controls>li{position:relative;background-position:center center;background-repeat:no-repeat;opacity:.4;transition:opacity 300ms ease}.lm_controls>li:hover{opacity:1}.lm_controls .lm_popout{background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAYAAADgkQYQAAAAPklEQVR4nI2Q0QoAIAwCNfr/X7aXCpGN8snBdgejJOzckpkxs9jR6K6T5JpU0nWl5pSXTk7qwh8SnNT+CAAWCgkKFpuSWsUAAAAASUVORK5CYII=)}.lm_controls .lm_maximise{background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAYAAADgkQYQAAAAKElEQVR4nGP8////fwYCgImQAgYGBgYWKM2IR81/okwajIpgvsMbVgAwgQYRVakEKQAAAABJRU5ErkJggg==)}.lm_controls .lm_close{background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAYAAADgkQYQAAAAQUlEQVR4nHXOQQ4AMAgCQeT/f6aXpsGK3jSTuCVJAAr7iBdoAwCKd0nwfaAdHbYERw5b44+E8JoBjEYGMBq5gAYP3usUDu2IvoUAAAAASUVORK5CYII=)}.lm_maximised .lm_header{background-color:#000000}.lm_maximised .lm_controls .lm_maximise{background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAJ0lEQVR4nGP8//8/AzGAiShVI1YhCwMDA8OsWbPwBmZaWhoj0SYCAN1lBxMAX4n0AAAAAElFTkSuQmCC)}.lm_transition_indicator{background-color:#000000;border:1px dashed #555555}.lm_popin{cursor:pointer}.lm_popin .lm_bg{background:#ffffff;opacity:.3}.lm_popin .lm_icon{background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAJCAYAAADpeqZqAAAAWklEQVR4nJWOyw3AIAxDHcQC7L8jbwT3AlJBfNp3SiI7dtRaLSlKKeoA1oEsKSQZCEluexw8Tm3ohk+E7bnOUHUGcNh+HwbBygw4AZ7FN/Lt84p0l+yTflV8AKQyLdcCRJi/AAAAAElFTkSuQmCC);background-position:center center;background-repeat:no-repeat;border-left:1px solid #eeeeee;border-top:1px solid #eeeeee;opacity:.7}.lm_popin:hover .lm_icon{opacity:1}/*# sourceMappingURL=goldenlayout-dark-theme.css.map */
          
          /* All the angular Treeview */
          .tree-children.tree-children-no-padding { padding-left: 0 }
          .tree-children { padding-left: 20px; overflow: hidden }
          .node-drop-slot { display: block; height: 2px }
          .node-drop-slot.is-dragging-over { background: #ddffee; height: 20px; border: 2px dotted #888; }
          .toggle-children-wrapper-expanded .toggle-children { transform: rotate(90deg) }
          .toggle-children-wrapper-collapsed .toggle-children { transform: rotate(0); }
          .toggle-children-wrapper {
            padding: 2px 3px 5px 1px;
          }
          /* tslint:disable */
          .toggle-children {
            background-color: white;
            height: 8px;
            width: 9px;
            background-size: contain;
            display: inline-block;
            position: relative;
            top: 1px;
            background-repeat: no-repeat;
            background-position: center;
          }
          .toggle-children-placeholder {
            display: inline-block;
            height: 10px;
            width: 10px;
            position: relative;
            top: 1px;
            padding-right: 3px;
          }
          .node-content-wrapper {
            display: inline-block;
            padding: 2px 5px;
            border-radius: 2px;
            transition: background-color .15s,box-shadow .15s;
          }
          .node-wrapper {display: flex; align-items: flex-start;}
          .node-content-wrapper-active,
          .node-content-wrapper.node-content-wrapper-active:hover,
          .node-content-wrapper-active.node-content-wrapper-focused {
            background: #beebff;
          }
          .node-content-wrapper-focused { background: #e7f4f9 }
          .node-content-wrapper:hover { background: #f7fbff }
          .node-content-wrapper-active, .node-content-wrapper-focused, .node-content-wrapper:hover {
            box-shadow: inset 0 0 1px #999;
          }
          .node-content-wrapper.is-dragging-over { background: #ddffee; box-shadow: inset 0 0 1px #999; }
          .node-content-wrapper.is-dragging-over-disabled { opacity: 0.5 }
          
          tree-viewport {
            -webkit-tap-highlight-color: transparent;
            height: 100%;
            overflow: auto;
            display: block;
          }
          .tree-children { padding-left: 20px }
          .empty-tree-drop-slot .node-drop-slot { height: 20px; min-width: 100px }
          .angular-tree-component {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;	
            font-size: 12px;	
            color: white;	
            width: 100%;
            position:relative;
            display: inline-block;
            cursor: pointer;
            -webkit-touch-callout: none; /* iOS Safari */
            -webkit-user-select: none;   /* Chrome/Safari/Opera */
            -khtml-user-select: none;    /* Konqueror */
            -moz-user-select: none;      /* Firefox */
            -ms-user-select: none;       /* IE/Edge */
            user-select: none;           /* non-prefixed version, currently not supported by any browser */
          }
          
          tree-root .angular-tree-component-rtl {
            direction: rtl;
          }
          tree-root .angular-tree-component-rtl .toggle-children-wrapper-collapsed .toggle-children {
            transform: rotate(180deg) !important;
          }
          tree-root .angular-tree-component-rtl .tree-children {
            padding-right: 20px;
            padding-left: 0;
          }
          
          tree-node-checkbox {
            padding: 1px;
          }
          '
â†“AppEvent [mobile.components.UIAppEvent-1587805424793]: 
  appEvent: onNetworkReachable